version: '3.1'

services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_db_stats
      - SPRING_DATASOURCE_USERNAME=ewm_stats_user
      - SPRING_DATASOURCE_PASSWORD=ewm_stats_pass

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_db_stats
      - POSTGRES_USER=ewm_stats_user
      - POSTGRES_PASSWORD=ewm_stats_pass

  ewm-service:
    build: ewm-main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db_main
      - SPRING_DATASOURCE_USERNAME=ewm_main_user
      - SPRING_DATASOURCE_PASSWORD=ewm_main_pass
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db_main
      - POSTGRES_USER=ewm_main_user
      - POSTGRES_PASSWORD=ewm_main_pass